### PR TITLE
Sonnet 2.0.2-1

### PR DESCRIPTION
**Pull request by ultrabear**
All we do is update deps to avoid some cryptography CVEs, im just taking the easy route with this patch release (instead of the normal direct push to main) because the CVEs dont actually affect sonnet, but we should still keep things up to date

### CODE REVIEW

**Comment by ultrabear** [comment]
looks like a new pyright lint is angry at us, good to rerun CI every once in a while for stuff like this

**Comment by ultrabear** [comment]
also removed deprecated dpy1.x stuff that pyright complained about being deprecated in 45b6e1112e53064e884f882e3da481e01fd23085, it was just dead code but worth cleaning up

**Review by bredo228 — APPROVED** [review]
Looks good

**Comment by ultrabear** [comment]
1. [x] Run `codespell`
1. [x] Open new version PR (`dev-unstable` -> `main`)
1. [x] Pass code review on new version PR
1. [x] Remove `-dev` tags from sonnet core modules (cmds and dlibs)
1. [x] Ensure all updated cmds and dlibs receive new version
1. [ ] ~~Decide on name for new version~~
1. [x] Locally create toml changelog in sonnet-website repository by referencing new version PR diff and commit history
1. [x] Locally update command reference on website using `cmds_to_html.py`
1. [x] Locally update latest version download link on website
1. [x] Export changelog without name to draft gh release and PR, using a new git tag for the new version
1. [x] Merge PR
1. [x] Immediately publish website changes and publish github release with new version name
1. [x] Post to sonnet support server that a new version was released
1. [x] Update instances we manage, mainly Summit and Remi
1. [ ] If any bugs occur, create new patch release and thoroughly test before publishing again

**Pull request merged**
